# Generated by Django 5.0.6 on 2024-06-02 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmodel',
            old_name='company_title',
            new_name='job_title',
        ),
    ]
